version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "michael-g"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pcatkpeq1n2w"
s3_prefix = "michael-g"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["SentimentFunction=681261969843.dkr.ecr.us-east-1.amazonaws.com/michaelgeed5dd95/sentimentfunction35d37012repo"]
